"""
fix_quantization_ignore.py

After transplant_mtp.py, the physical tensors
mtp.layers.0.self_attn.{q,k,v,o}_proj and
mtp.layers.0.mlp.{gate,up,down}_proj have become plain bf16 tensors.
However, the quantization_config generated by llm-compressor during calibration
still considers them quantized (because the recipe did not exclude them;
calibration simply "compressed" them blindly without actual activation
statistics).

Add these modules to the ignore list so that the config matches the actual
data stored on disk.

Run this AFTER patch_config.py (when quantization_config is already final).
"""

import argparse
import json


# These 7 are large matrices and remain QUANTIZED (block-FP8), so they must NOT
# be added to ignore. Instead, they get their own config_group below.
MTP_BLOCK_QUANTIZED_MODULES = [
    "mtp.layers.0.self_attn.q_proj",
    "mtp.layers.0.self_attn.k_proj",
    "mtp.layers.0.self_attn.v_proj",
    "mtp.layers.0.self_attn.o_proj",
    "mtp.layers.0.mlp.gate_proj",
    "mtp.layers.0.mlp.up_proj",
    "mtp.layers.0.mlp.down_proj",
]

# These 8 are norms/gates. They were already non-Linear / non-quantized before,
# so they remain simply in ignore, as before.
MTP_IGNORE_MODULES = [
    "mtp.fc",
    "mtp.norm",
    "mtp.pre_fc_norm_embedding",
    "mtp.pre_fc_norm_hidden",
    "mtp.layers.0.input_layernorm",
    "mtp.layers.0.post_attention_layernorm",
    "mtp.layers.0.self_attn.k_norm",
    "mtp.layers.0.self_attn.q_norm",
]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True, help="config.json of the target checkpoint")
    args = parser.parse_args()

    with open(args.config, "r", encoding="utf-8") as f:
        config = json.load(f)

    qconfig = config.get("quantization_config")

    if qconfig is None:
        print(
            "No quantization_config found in config.json — nothing to modify. "
            "Check the path/file."
        )
        return

    ignore = qconfig.get("ignore", [])
    added_to_ignore = []

    for module in MTP_IGNORE_MODULES:
        if module not in ignore:
            ignore.append(module)
            added_to_ignore.append(module)

    qconfig["ignore"] = ignore

    # IMPORTANT: if these 7 paths were previously added to ignore
    # (for example, if you already ran an older version of this script on the
    # same config.json), remove them. Otherwise, the configuration would be
    # contradictory: the paths would be both "do not quantize" (ignore) and
    # "quantize using block-wise scheme" (config_groups).
    removed_from_ignore = []

    for module in MTP_BLOCK_QUANTIZED_MODULES:
        if module in ignore:
            ignore.remove(module)
            removed_from_ignore.append(module)

    config_groups = qconfig.setdefault("config_groups", {})

    config_groups["group_mtp_block"] = {
        "targets": MTP_BLOCK_QUANTIZED_MODULES,
        "weights": {
            "num_bits": 8,
            "type": "float",
            "strategy": "block",
            "block_structure": [128, 128],
            "dynamic": False,
            "symmetric": True,
        },
        "input_activations": {
            "num_bits": 8,
            "type": "float",
            "strategy": "token",
            "dynamic": True,
            "symmetric": True,
        },
    }

    config["quantization_config"] = qconfig

    print(f"Added to ignore (norms/gates): {added_to_ignore}")

    if removed_from_ignore:
        print(
            f"Removed from ignore (now quantized using block-wise scheme): "
            f"{removed_from_ignore}"
        )

    print(
        "Added quantization_config.config_groups.group_mtp_block"
    )

    backup_path = args.config + ".bak2"

    with open(backup_path, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2, ensure_ascii=False)

    print(f"Additional backup created before modification: {backup_path}")

    with open(args.config, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2, ensure_ascii=False)

    print(f"Written to {args.config}")


if __name__ == "__main__":
    main()
